dist: bionic
language: bash
branches:
  only:
    - dev
    - stg
    - prd
env:
  ### --------------------------------------------------
  ### Find and Replace
  - TF_VAR_app_name=tfmultienv
  - TF_VAR_region=eu-west-1
  - AWS_REGION=eu-west-1
  - AWS_DEFAULT_REGION=eu-west-1
  ### --------------------------------------------------
  - TERRAFORM_VERSION=0.13.1
  - LIVE_DIR=live
  - BACKEND_TPL=backend.tf.tpl

jobs:
  include:
    - stage: prepare-files-folders
      script:
        - ./scripts/prepare-files-folders.sh
    - stage: prepare-backend
      script:
        - declare -n AWS_ACCESS_KEY_ID_SECRET_NAME=aws_access_key_id_${CIRCLE_BRANCH}
        - declare -n AWS_SECRET_ACCESS_KEY_SECRET_NAME=aws_secret_access_key_${CIRCLE_BRANCH}
        - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_SECRET_NAME}
        - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_SECRET_NAME}
        - docker run --rm -w="/code" -e TF_VAR_app_name -e TF_VAR_region -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e BRANCH_NAME=$TRAVIS_BRANCH -v "${HOME}"/project/:/code/ unfor19/terraform-alpine:$TERRAFORM_VERSION /code/scripts/prepare-backend.sh
