version: 2.1
workflows:
  pipeline:
    when:
      condition:
        or:
          - equal: [development, << pipeline.git.branch >>]
          - equal: [staging, << pipeline.git.branch >>]
          - equal: [production, << pipeline.git.branch >>]
    jobs:
      - terraform-apply

jobs:
  terraform-apply:
    machine: true
    steps:
      - checkout
      - run:
          name: terraform-apply
          command: |
            docker run --rm -w="/code" -e CIRCLE_BRANCH -v "${HOME}"/project/:/code/ unfor19/terraform-alpine:0.12.28 /code/scripts/tf-apply-circleci.sh
