version: 2.1
workflows:
  pipeline:
    when:
      condition:
        or:
          - equal: [development, << pipeline.git.branch >>]
          - equal: [staging, << pipeline.git.branch >>]
          - equal: [production, << pipeline.git.branch >>]
    jobs:
      - terraform-apply

jobs:
  terraform-apply:
    machine:
      image:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: terraform-apply
          command: |
            docker run --rm -w="${CIRCLE_WORKING_DIRECTORY}" -e CIRCLE_BRANCH -v ${CIRCLE_WORKING_DIRECTORY}/:${CIRCLE_WORKING_DIRECTORY}/ unfor19/terraform-alpine:0.12.28 /code/tf-apply-circleci.sh
